### ISSUE TITLE
Issues when using rule34.xxx

### ISSUE THREAD

**Issue by okacu95** [asadahimeka/yandere-masonry#20]
When viewing on the waterfall mode it seems to pull the search and shows the results. however when doing the same on some ones favorites' there is no search and shows the same as if the search was blank. 

Favorites url:
rule34.xxx/index.php?page=favorites&s=view&id=342018&pid=42

normal url:
https://rule34.xxx/index.php?page=post&s=list&tags=all

Would be good if this code worked for favorites too.

Thanks !

**Comment by asadahimeka** [comment]
This link is not adapted, I will fix it when I have time.

**Comment by asadahimeka** [comment]
@okacu95 , 

Sorry for the late reply. 

Recently I took the time to adapt r34 favorites page and v0.30.0 has been released. 

Because I didn't find the detailed API documentation of r34, this is just a simple crawler adaptation, with some missing functions and possible problems. 

You can try it to see if it meets your needs.
