### ISSUE TITLE
[Feature]: Make navigation possible via keyboard

### ISSUE THREAD

**Issue by EnergoStalin** [asadahimeka/yandere-masonry#31]
Elements that cant be navigated with [Vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) and so can't conviniently with keyboard.

- Images in flow view Vimium don't treat \<div> tags as clickable element.
![image](https://github.com/asadahimeka/yandere-masonry/assets/49844515/15892ced-fe41-40e1-bc62-a382e72b787e)
- Tag list in image view
- Post link
![image](https://github.com/asadahimeka/yandere-masonry/assets/49844515/2d003780-c6ca-4a52-a273-e9ffa6ba289d)

**Comment by asadahimeka** [comment]
Partially supported in v0.32.2.
Due to some limitations, list images keyboard navigation only works when layout is set to `Justified`.
And only the tag list in image view of yande.re or konachan can be clicked.
![2024-4-14 18-25-6](https://github.com/asadahimeka/yandere-masonry/assets/31837214/ff84ee41-f301-44b6-943e-dffc28e2d1c2)
![2024-4-14 18-33-0](https://github.com/asadahimeka/yandere-masonry/assets/31837214/72ad38f1-3f93-49b9-a374-b4e160c7db50)

**Comment by EnergoStalin** [comment]
> And only the tag list in image view of yande.re or konachan can be clicked.

Doubt so.
![image](https://github.com/asadahimeka/yandere-masonry/assets/49844515/cf9b1ed1-6138-43c1-98aa-3ad4b62eaf81)

Good job anyway! That's all i wanted thanks.
